version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
  django:
    build: .
    image: prash9/bhavcopyequity
    container_name: django
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis