version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
  django:
    build: .
    image: bhavcopy_django
    container_name: django
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis